### ISSUE TITLE
Stucked at 'preparing file'

### ISSUE THREAD

**Issue by graphenepay** [Storj/integration#6]
When running docker straight from a git clone, uploading files is impossible.
After a long time of 'Preparing file', the process exists with 'Unable to receive storage offer'.

**Comment by braydonf** [comment]
Yeah, need to merge in https://github.com/Storj/integration/pull/5

**Comment by graphenepay** [comment]
I'm trying to figure out how to run a bridge detached from the official one, for later purposes. Support told me to take a look at this repo, but if it's broken as well, it has no use.

**Comment by braydonf** [comment]
Try latest master.

**Comment by braydonf** [comment]
You may need to run with `docker build -t storj-integration . --no-cache`

**Comment by graphenepay** [comment]
Commit f3a5937 gives same issues. Removed docker container, fresh docker install, same problem.

**Comment by braydonf** [comment]
Yeah, getting the same also, looking at it now.

**Comment by graphenepay** [comment]
This repo seemed usefull as i'm trying to run my own bridge and nodes, since there is very little documentation available about it. If you would have some detailed information, it would help me out as well.

**Comment by braydonf** [comment]
Okay it's fixed in 07d8afaf970237925402050f7e56b78824942559. I forget to leave `activateSIP6` as `false`, since there are still a few updates needed to storjshare for that to work.

**Comment by graphenepay** [comment]
That did it. Well done.
Could you briefly explain what changes have been made so i can extend this to my full version?

When setting up bridge, complex, ... apart, i got the same error. This is the very reason why I looked in this repo for a fix.

**Comment by braydonf** [comment]
We're in the middle of switching to enable SIP6 to resolve upload issues.

**Comment by graphenepay** [comment]
Okay. The docker version is running fine now, but i'm still unable to connect any external storj-share daemon or GUI to the running network :/ Even with the seeds filled in the config, it gets no peers and get-contacts doens't list it either

**Comment by braydonf** [comment]
I have not tried running storjshare externally. The goal has been to run a sandboxed network for development purposes. With the small exception that a few ports are open for making file transfers.

**Comment by braydonf** [comment]
As far as what changes were needed, you can see those in: https://github.com/Storj/integration/pull/5
